import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, FileBarChart, FileText, Repeat } from "lucide-react";

import { DataScreen } from "@/components/marketing/data-screen";
import { StatusBadge } from "@/components/marketing/kit";
import { dateTime, num, titleCase } from "@/lib/marketing/format";

export const Route = createFileRoute("/marketing/reports")({
  head: () => ({
    meta: [
      { title: "Reports — Software Vala Marketing Manager" },
      {
        name: "description",
        content:
          "Generate and track marketing performance, attribution and spend reports across periods and formats.",
      },
      { property: "og:title", content: "Reports — Software Vala" },
      {
        property: "og:description",
        content: "Marketing reporting library with periods, formats and generation status.",
      },
    ],
  }),
  component: ReportsScreen,
});

const REPORT_TYPES = [
  "performance",
  "attribution",
  "spend",
  "seo",
  "lead_quality",
  "creative",
  "executive_summary",
] as const;
const PERIODS = ["daily", "weekly", "monthly", "quarterly", "yearly", "custom"] as const;
const FORMATS = ["pdf", "csv", "xlsx", "dashboard"] as const;
const STATUSES = ["queued", "generating", "ready", "failed", "archived"] as const;

function ReportsScreen() {
  return (
    <DataScreen
      table="marketing_reports"
      title="Reports"
      description="Every generated marketing report with period, format and delivery state."
      module="Reports"
      entityLabel="Report"
      order={{ column: "generated_at" }}
      searchKeys={["name", "report_type", "generated_by", "period"]}
      filterKey="status"
      filterOptions={STATUSES}
      minWidth={1000}
      stats={[
        { label: "Reports", icon: FileText, tone: "violet", value: (r) => num(r.length) },
        {
          label: "Ready",
          icon: CheckCircle2,
          tone: "green",
          value: (r) => num(r.filter((x) => x.status === "ready").length),
        },
        {
          label: "Recurring periods",
          icon: Repeat,
          tone: "blue",
          value: (r) => num(new Set(r.map((x) => x.period)).size),
        },
        {
          label: "Report types",
          icon: FileBarChart,
          tone: "gold",
          value: (r) => num(new Set(r.map((x) => x.report_type)).size),
        },
      ]}
      columns={[
        { key: "name", header: "Report", render: (r) => <span className="font-medium">{r.name}</span> },
        { key: "report_type", header: "Type", render: (r) => titleCase(r.report_type) },
        { key: "period", header: "Period", render: (r) => titleCase(r.period) },
        { key: "format", header: "Format", render: (r) => r.format.toUpperCase() },
        { key: "status", header: "Status", render: (r) => <StatusBadge value={r.status} /> },
        { key: "generated_at", header: "Generated", render: (r) => dateTime(r.generated_at) },
        { key: "generated_by", header: "By", render: (r) => r.generated_by ?? "—" },
        { key: "summary", header: "Summary", render: (r) => r.summary ?? "—" },
      ]}
      fields={[
        { key: "name", label: "Report name", kind: "text", required: true, full: true },
        { key: "report_type", label: "Report type", kind: "select", options: REPORT_TYPES },
        { key: "period", label: "Period", kind: "select", options: PERIODS },
        { key: "format", label: "Format", kind: "select", options: FORMATS },
        { key: "status", label: "Status", kind: "select", options: STATUSES },
        { key: "generated_by", label: "Generated by", kind: "text" },
        { key: "generated_at", label: "Generated at", kind: "datetime" },
        { key: "summary", label: "Summary", kind: "textarea", full: true },
      ]}
    />
  );
}
